redis:
  addr: "localhost:6379"
  password: ""
  db: 0

mysql:
  name: "institution"
  password: "institution"
  addr: "localhost:3306"
  db: "institution"

server:
  port: 9001

admin:
  username: "verysimon"
  password: "123456"
